package com.digital.vegamoviee
import com.lagradost.cloudstream3.*
import com.lagradost.cloudstream3.utils.*
import org.jsoup.nodes.Element
import java.net.URLEncoder
class VegaMoviee:MainAPI(){
 override var mainUrl="https://vegamoviee.com";override var name="VegaMoviee";override var lang="hi";override val supportedTypes=setOf(TvType.Movie,TvType.TvSeries);override val hasMainPage=true;override val hasQuickSearch=true
 override val mainPage=mainPageOf(mainUrl to "Latest","$mainUrl/category/bollywood/" to "Bollywood","$mainUrl/category/hollywood/" to "Hollywood","$mainUrl/category/web-series/" to "Web Series","$mainUrl/category/dual-audio/" to "Dual Audio","$mainUrl/category/korean/" to "Korean","$mainUrl/category/anime-series/" to "Anime","$mainUrl/category/netflix/" to "Netflix","$mainUrl/category/prime-video/" to "Prime Video","$mainUrl/category/south-hindi/" to "South Hindi")
 private val h=mapOf("User-Agent" to "Mozilla/5.0")
 override suspend fun getMainPage(page:Int,request:MainPageRequest):HomePageResponse{val d=app.get(if(page==1)request.data else "${request.data.trimEnd('/')}/page/$page/",headers=h,referer=mainUrl).document;return newHomePageResponse(request.name,items(d),d.selectFirst("a.next, a.next.page-numbers, link[rel=next]")!=null)}
 override suspend fun search(query:String,page:Int):SearchResponseList{val q=URLEncoder.encode(query.trim(),"UTF-8");val d=app.get(if(page==1)"$mainUrl/?s=$q" else "$mainUrl/page/$page/?s=$q",headers=h,referer=mainUrl).document;return newSearchResponseList(items(d),d.selectFirst("a.next, a.next.page-numbers, link[rel=next]")!=null)}
 override suspend fun quickSearch(query:String)=search(query,1).items
 override suspend fun load(url:String):LoadResponse{val d=app.get(url,headers=h,referer=mainUrl).document;val title=d.selectFirst("h1.entry-title,h1")?.text()?.trim()?:d.selectFirst("meta[property=og:title]")?.attr("content")?:"VegaMoviee";val poster=d.selectFirst("meta[property=og:image]")?.attr("content");val plot=d.selectFirst("meta[name=description],meta[property=og:description]")?.attr("content");val links=d.select(".entry-content a[href]").map{it.absUrl("href")}.filter{it.startsWith("http")&&!it.contains("vegamoviee.com")};return newMovieLoadResponse(title,url,TvType.Movie,url){posterUrl=poster;this.plot=plot;recommendations=d.select("article.post-item").mapNotNull{it.toResult()}}}
 override suspend fun loadLinks(data:String,isCasting:Boolean,subtitleCallback:(SubtitleFile)->Unit,callback:(ExtractorLink)->Unit):Boolean{val d=app.get(data,headers=h,referer=mainUrl).document;var f=false;d.select(".entry-content a[href]").forEach{val u=it.absUrl("href");if(u.startsWith("http")&&!u.contains(mainUrl)&&loadExtractor(u,data,subtitleCallback,callback))f=true};Regex("https?[^\\\"' ]+\\.(?:mp4|mkv|m3u8)(?:\\?[^\\\"' ]*)?",RegexOption.IGNORE_CASE).findAll(d.html()).forEach{callback(newExtractorLink(name,"Direct",it.value,if(it.value.contains("m3u8"))ExtractorLinkType.M3U8 else ExtractorLinkType.VIDEO){referer=data});f=true};return f}
 private fun items(d:org.jsoup.nodes.Document)=d.select("article.post-item").mapNotNull{it.toResult()}.distinctBy{it.url}
 private fun Element.toResult():SearchResponse?{val a=selectFirst("h3.entry-title a[href],h2.entry-title a[href],a.blog-img[href]")?:return null;val u=a.absUrl("href");if(!u.startsWith(mainUrl))return null;val t=selectFirst("h3.entry-title,h2.entry-title")?.text()?.trim()?:a.attr("title").trim();if(t.isBlank())return null;val p=selectFirst("img")?.let{it.absUrl("src").ifBlank{it.attr("data-src")}};return if(t.contains(Regex("(?i)series|season|episode")))newTvSeriesSearchResponse(t,u,TvType.TvSeries){posterUrl=p}else newMovieSearchResponse(t,u,TvType.Movie){posterUrl=p}}
}
